# Generated by Django 2.1.5 on 2019-02-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentee',
            new_name='Mentor',
        ),
    ]
