# Generated by Django 2.1.5 on 2019-02-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('quote', models.TextField(max_length=255)),
                ('photo', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
