# Generated by Django 2.1.5 on 2019-02-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='photo',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
