# Generated by Django 2.1.5 on 2019-02-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_auto_20190212_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='photo',
            field=models.FileField(null=True, upload_to='mentee/', verbose_name=''),
        ),
    ]
